import React from "react";
import Head from "next/head"; // Import the Head component from next/head

const PageHead = () => {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by Create Next App" />
      <link rel="icon" href="/logo.png" type="image/x-icon" /> {/* Corrected the icon path */}
    </Head>
  );
};

export default PageHead;
